---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: tomcat-9
    image: tomcat:9-jdk17-temurin
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/jenkins.war:/usr/local/tomcat/webapps/jenkins.war
  - name: wildfly-26
    image: quay.io/wildfly/wildfly:26.1.3.Final-jdk17
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/jenkins.war:/opt/jboss/wildfly/standalone/deployments/jenkins.war
provisioner:
  name: ansible
  inventory:
    host_vars:
      wildfly-26:
        ansible_python_interpreter: "/usr/bin/python3"
verifier:
  name: ansible
