---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: tomcat-9
    image: tomcat:9-jdk17-temurin
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/jenkins.war:/usr/local/tomcat/webapps/jenkins.war
provisioner:
  name: ansible
verifier:
  name: ansible
