# vim: set ft=ruby ts=2 sts=2 sw=2 :

# expand references to parameters in Makefile
def translate(script)
  `cp #{script} #{script}.generated`
  `../bin/branding.sh #{script}.generated`
  script+".generated"
end

def box(config,name,image)
  config.vm.define(name) do |node|
    node.vm.box = image
    node.vm.provision :shell, path:translate("provision/#{name}.sh")
    node.vm.provision :serverspec do |spec|
      spec.pattern = 'spec/#{name}_spec.rb'
    end
  end
end

Vagrant.configure("2") do |config|
  box(config,"rpm",  "chef/fedora-20")
  box(config,"suse", "chef/opensuse-13.1")
  box(config,"deb",  "chef/ubuntu-12.04")
end
