# vim: set ft=ruby ts=2 sts=2 sw=2 :

# expand references to parameters in Makefile
def translate(script)
end

`[ -d provision/generated ] || mkdir provision/generated`
`cp -R provision/*.sh provision/generated`
`../bin/branding.sh provision/generated`

def box(config,name,image)
  config.vm.define(name) do |node|
    node.vm.box = image
    node.vm.provision :shell, path:"provision/generated/#{name}.sh"
    node.vm.provision :serverspec do |spec|
      spec.pattern = "spec/#{name}_spec.rb"
    end
  end
end

Vagrant.configure("2") do |config|
  box(config,"rpm",  "chef/fedora-20")
  box(config,"suse", "chef/opensuse-13.1")
  box(config,"deb",  "chef/ubuntu-12.04")
end
