# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Starting with 7.x, Ansible requires Python >=3.9, which our Ubuntu
      # 20.04-based agent VMs do not provide.
      - dependency-name: "ansible"
        versions: [">=7.0.0"]
