#!/bin/bash

#####
##    THIS FILE IS TO BE DELETED BEFORE MERGE
#####

set -x

# Use weekly 2.234
VERSION=2.234

# Use pre-release prototype 2.226 from 15 Apr 2020
# VERSION=2.226

declare -A PKG

if hostname --all-ip-addresses | grep -q -F 172.16.16; then

  # markwaite.net
  PKG[centos]=https://home.markwaite.net/~mwaite/jenkins-builds/${VERSION}/jenkins-${VERSION}-1.1.noarch.rpm
  PKG[debian]=https://home.markwaite.net/~mwaite/jenkins-builds/${VERSION}/jenkins_${VERSION}_all.deb
  PKG[msi]=https://home.markwaite.net/~mwaite/jenkins-builds/${VERSION}/jenkins-${VERSION}.zip
  PKG[suse]=https://home.markwaite.net/~mwaite/jenkins-builds/${VERSION}/jenkins-${VERSION}-1.2.noarch.rpm
  PKG[war]=https://home.markwaite.net/~mwaite/jenkins-builds/${VERSION}/jenkins.war

else

  # everywhere else
  PKG[centos]=https://pkg.jenkins.io/redhat/jenkins-${VERSION}-1.1.noarch.rpm
  PKG[debian]=https://pkg.jenkins.io/debian/binary/jenkins_${VERSION}_all.deb
  PKG[msi]=http://mirrors.jenkins-ci.org/windows/jenkins-${VERSION}.zip
  PKG[suse]=https://pkg.jenkins.io/opensuse/jenkins-${VERSION}-1.2.noarch.rpm
  PKG[war]=http://mirrors.jenkins-ci.org/war/${VERSION}/jenkins.war

fi

[ -d results ] && rm -rf results

# Fresh start with new target files
rm -rf target

# Once a day refresh the cache of target files
[ -d target ] && find target -mindepth 1 -mtime +1 -delete

[ -d target ] || mkdir target

[ -d target/centos ] || mkdir target/centos
if ! ls target/centos/*.rpm > /dev/null 2>&1; then
    ( cd target/centos && wget --no-use-server-timestamps -q ${PKG[centos]} )
    if ! ls target/centos/*.rpm | grep -q rpm; then
      echo "No CentOS rpm file in target/centos/"
      exit 1
    fi
fi

[ -d target/debian ] || mkdir target/debian
if ! ls target/debian/*.deb > /dev/null 2>&1; then
    ( cd target/debian && wget --no-use-server-timestamps -q ${PKG[debian]} )
    if ! ls target/debian/*.deb | grep -q deb; then
      echo "No Debian deb file in target/debian/"
      exit 2
    fi
fi

[ -d target/msi ] || mkdir target/msi
if ! ls target/msi/*.msi > /dev/null 2>&1; then
    ( cd target/msi && wget --no-use-server-timestamps -q ${PKG[msi]} && unzip *.zip && touch *.msi )
    if ! ls target/msi/*.msi | grep -q msi; then
      echo "No MSI file in target/msi/"
      exit 3
    fi
fi

[ -d target/suse ] || mkdir target/suse
if ! ls target/suse/*.rpm > /dev/null 2>&1; then
    ( cd target/suse && wget --no-use-server-timestamps -q ${PKG[suse]} )
    if ! ls target/suse/*.rpm | grep -q rpm; then
      echo "No SuSE rpm file in target/suse/"
      exit 4
    fi
fi

[ -d target/war ] || mkdir target/war
if ! ls target/war/*.war > /dev/null 2>&1; then
    ( cd target/war && wget --no-use-server-timestamps -q ${PKG[war]} )
    if ! ls target/war/*.war | grep -q war; then
      echo "No Java war file in target/war/"
      exit 5
    fi
fi

WAR=target/war/*.war MSI=target/msi/*.msi make docker.test
