---
- command:
    cmd: amazon-linux-extras install java-openjdk11 -y
    creates: /usr/lib/jvm/jre-11-openjdk
  when: ansible_distribution == 'Amazon'
- package:
    name:
      - fontconfig
      - java-11-openjdk
    state: present
    update_cache: true
- file:
    path: /var/tmp/target/credentials
    state: directory
- copy:
    src: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/credentials/test.ascii.key"
    dest: /var/tmp/target/credentials/test.ascii.key
- rpm_key:
    state: present
    key: /var/tmp/target/credentials/test.ascii.key
- find:
    paths: /var/tmp/target/rpm
    file_type: file
    patterns: "*.rpm"
  register: package_list
- assert:
    that:
      - package_list.matched == 1
- package:
    name: "{{ package_list.files[0].path }}"
    state: present
