---
- command:
    cmd: amazon-linux-extras install java-openjdk11 -y
    creates: /usr/lib/jvm/jre-11-openjdk
  when: ansible_distribution == 'Amazon'
- package:
    name:
      - fontconfig
      - initscripts
      - java-11-openjdk
    disable_gpg_check: true  # TODO get this working
    state: present
    update_cache: true
- find:
    paths: /var/tmp/target/rpm
    file_type: file
    patterns: "*.rpm"
  register: package_list
- assert:
    that:
      - package_list.matched == 1
- package:
    name: "{{ package_list.files[0].path }}"
    disable_gpg_check: true  # TODO get this working
    state: present
- lineinfile:
    path: /etc/sysconfig/jenkinstest
    regexp: '^JENKINS_JAVA_OPTIONS='
    line: "JENKINS_JAVA_OPTIONS=\"-Djava.awt.headless=true -Xmx256m\""
- systemd:
    daemon_reload: true
  when: ansible_service_mgr == 'systemd'
