---
- dnf:
    name:
      - epel-release
    disable_gpg_check: true  # TODO get this working
    state: present
    update_cache: true
  when: ansible_distribution != 'Fedora' and ansible_distribution != 'OracleLinux'
- yum_repository:
    name: oracle-linux-epel
    description: "Oracle Linux {{ ansible_distribution_major_version }} EPEL ($basearch)"
    baseurl: "https://yum.oracle.com/repo/OracleLinux/OL{{ ansible_distribution_major_version }}/developer/EPEL/$basearch/"
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
    gpgcheck: true
    enabled: true
  when: ansible_distribution == 'OracleLinux'
- dnf:
    name:
      - daemonize
      - dejavu-sans-fonts
      - fontconfig
      - freetype
      - initscripts
      - java-11-openjdk
    disable_gpg_check: true  # TODO get this working
    state: present
    update_cache: true
- find:
    paths: /var/tmp/target/rpm
    file_type: file
    patterns: "*.rpm"
  register: package_list
- assert:
    that:
      - package_list.matched == 1
- dnf:
    name: "{{ package_list.files[0].path }}"
    disable_gpg_check: true  # TODO get this working
    state: present
- lineinfile:
    path: /etc/sysconfig/jenkinstest
    regexp: '^JENKINS_JAVA_OPTIONS='
    line: "JENKINS_JAVA_OPTIONS=\"-Djava.awt.headless=true -Xmx256m\""
- systemd:
    daemon_reload: true
  when: ansible_service_mgr == 'systemd'
