---
- package:
    name:
      - dejavu-fonts
      - fontconfig
      - java-11-openjdk
    disable_gpg_check: true  # TODO get this working
    state: present
    update_cache: true
- find:
    paths: /var/tmp/target/suse
    file_type: file
    patterns: "*.rpm"
  register: package_list
- assert:
    that:
      - package_list.matched == 1
- package:
    name: "{{ package_list.files[0].path }}"
    disable_gpg_check: true  # TODO get this working
    state: present
