---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: fedora-41
    image: dokken/fedora-41:latest
    override_command: false
    volumes:
      - ./target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml

verifier:
  name: ansible
