---
dependency:
  name: galaxy
driver:
  name: docker

platforms:
  # deb
  - name: debian-11  # EOL 2026-06-30
    image: dokken/debian-11:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  - name: debian-12  # EOL 2028-06-10
    image: dokken/debian-12:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  - name: ubuntu-20-04  # EOL 2025-04-02
    image: dokken/ubuntu-20.04:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  - name: ubuntu-22-04  # EOL 2027-04-01
    image: dokken/ubuntu-22.04:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  - name: ubuntu-24-04  # EOL 2029-04-01
    image: dokken/ubuntu-24.04:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  # rpm
  - name: almalinux-9  # EOL 2027-05-31
    image: dokken/almalinux-9:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  - name: amazonlinux-2023  # EOL 2025-03-15
    image: dokken/amazonlinux-2023:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  - name: centos-stream-9  # EOL 2027-05-31
    image: dokken/centos-stream-9:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  - name: eurolinux-9  # EOL 2032-06-30
    image: dokken/eurolinux-9:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  - name: fedora-40  # EOL 2025-05-13
    image: dokken/fedora-40:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  - name: oraclelinux-8  # EOL 2029-07-01
    image: dokken/oraclelinux-8:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  - name: oraclelinux-9  # EOL 2032-06-30
    image: dokken/oraclelinux-9:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  - name: rockylinux-9  # EOL 2025-05-31
    image: dokken/rockylinux-9:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  # suse
  - name: opensuse-leap-15.5  # EOL 2024-12-01
    image: dokken/opensuse-leap-15.5:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  - name: opensuse-leap-15.6  # EOL 2025-12-01
    image: dokken/opensuse-leap-15.6:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
