---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-22-04
    image: dokken/ubuntu-22.04:latest
    command: /sbin/init
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
  - name: fedora-35
    image: dokken/fedora-35:latest
    command: /sbin/init
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
  - name: opensuse-leap-15
    image: dokken/opensuse-leap-15:latest
    command: /sbin/init
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
