---
dependency:
  name: galaxy
driver:
  name: docker

platforms:
  # deb
  - name: debian-10
    image: dokken/debian-10:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  - name: debian-11
    image: dokken/debian-11:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  - name: ubuntu-18-04
    image: dokken/ubuntu-18.04:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  - name: ubuntu-20-04
    image: dokken/ubuntu-20.04:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  - name: ubuntu-22-04
    image: dokken/ubuntu-22.04:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  # rpm
  - name: almalinux-8
    image: dokken/almalinux-8:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  - name: almalinux-9
    image: dokken/almalinux-9:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  - name: amazonlinux-2
    image: dokken/amazonlinux-2:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  - name: centos-stream-8
    image: dokken/centos-stream-8:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  - name: centos-stream-9
    image: dokken/centos-stream-9:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  - name: fedora-36
    image: dokken/fedora-36:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  - name: oraclelinux-8
    image: dokken/oraclelinux-8:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  - name: oraclelinux-9
    image: dokken/oraclelinux-9:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  - name: rockylinux-8
    image: dokken/rockylinux-8:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  - name: rockylinux-9
    image: dokken/rockylinux-9:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
  # suse
  - name: opensuse-leap-15
    image: dokken/opensuse-leap-15:latest
    override_command: false
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/target:/var/tmp/target
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
