---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: fedora-41
    image: dokken/fedora-41:latest
    override_command: false
    volumes:
      - /home/jenkins/agent/workspace/Packaging_packaging_PR-536/target/rpm:/var/tmp/target/rpm
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml

verifier:
  name: ansible
