---
- name: Verify
  hosts: all
  tasks:
  - file:
      path: /etc/systemd/system/jenkins.service.d
      state: directory
    when: ansible_service_mgr == 'systemd'
  - stat:
      path: /etc/systemd/system/jenkins.service.d/override.conf
    register: drop_in
    when: ansible_service_mgr == 'systemd'
  - assert:
      that:
        - not drop_in.stat.exists
  - copy:
      dest: /etc/systemd/system/jenkins.service.d/override.conf
      content: |
        [Service]
        Environment="JAVA_OPTS=-Djava.awt.headless=true -Xmx256m -Dhudson.model.DirectoryBrowserSupport.CSP=\"default-src 'self';\""
        TimeoutStartSec=600
    when: ansible_service_mgr == 'systemd'
  - systemd:
      daemon_reload: true
    when: ansible_service_mgr == 'systemd'
  - pids:
      name: java
    register: service_pids
  - assert:
      that:
        - (service_pids.pids | length) == 0
      fail_msg: "{{ service_pids.pids|join(',') }}"
  - service:
      name: jenkins
      state: started
  - uri:
      url: "http://127.0.0.1:8080"
      status_code: 403
    register: result
    until: result.status == 403
    retries: 20
    delay: 5
  - pids:
      name: java
    register: service_pids
  - assert:
      that:
        - (service_pids.pids | length) == 1
      fail_msg: "{{ service_pids.pids | join(',') }}"
  - service:
      name: jenkins
      state: stopped
  - pids:
      name: java
    register: service_pids
  - assert:
      that:
        - (service_pids.pids | length) == 0
      fail_msg: "{{ service_pids.pids | join(',') }}"
