---
- name: Verify
  hosts: all
  tasks:
  - pids:
      name: java
    register: service_pids
  - assert:
      that:
        - (service_pids.pids | length) == 0
      fail_msg: "{{ service_pids.pids|join(',') }}"
  - service:
      name: jenkinstest
      state: started
  - uri:
      url: "http://127.0.0.1:7777"
      status_code: 403
    register: result
    until: result.status == 403
    retries: 20
    delay: 5
  - pids:
      name: java
    register: service_pids
  - assert:
      that:
        - (service_pids.pids | length) == 1
      fail_msg: "{{ service_pids.pids | join(',') }}"
  - service:
      name: jenkinstest
      state: stopped
  - pids:
      name: java
    register: service_pids
  - assert:
      that:
        - (service_pids.pids | length) == 0
      fail_msg: "{{ service_pids.pids | join(',') }}"
