---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - block:
      - service:
          name: jenkinstest
          state: started
    rescue:
      - command: journalctl -u jenkinstest.service
        register: journal_output
      - debug:
          msg: "{{ journal_output }}"
  - uri:
      url: "http://127.0.0.1:7777"
      status_code: 403
    register: result
    until: result.status == 403
    retries: 60
    delay: 1
  - service:
      name: jenkinstest
      state: stopped
