#!/bin/bash

JENKINS_PLIST="/Library/LaunchDaemons/@@OSX_IDPREFIX@@.plist"

# Because PackageMaker just copies the components, we need to fix the permissions
chown root:wheel ${JENKINS_PLIST}
chmod 644 ${JENKINS_PLIST}
mkdir -p /Users/Shared/@@CAMELARTIFACTNAME@@
find /Users/Shared/@@CAMELARTIFACTNAME@@ \( -not -user daemon -or -not -group daemon \) -print0 | xargs -0 chown daemon:daemon

# Create log directory, which can be written by Jenkins daemon
mkdir -p /var/log/@@ARTIFACTNAME@@
chown daemon:daemon /var/log/@@ARTIFACTNAME@@

# Enable log rotation by newsyslog
cat <<_EOT_ > /etc/newsyslog.d/@@ARTIFACTNAME@@.conf
# logfilename          [owner:group]    mode count size when  flags [/pid_file] [sig_num]
# Rotate @@PRODUCTNAME@@ log at midnight, and preserve old logs in 3 days
/var/log/@@ARTIFACTNAME@@/@@ARTIFACTNAME@@.log            644  3     *    \$D0   J
_EOT_

# Load and start the launch daemon
/bin/launchctl load -w ${JENKINS_PLIST}

# Wait for port 8080 to start accepting connections.
# But don't wait forever.
timeout=$(($(date +%s) + 60))
while [ $(date +%s) -lt $timeout ] && ! curl -s http://localhost:@@PORT@@ >/dev/null; do
    sleep 1
done

if [ $(date +%s) -ge $timeout ]; then
    echo "Timed out waiting for @@PRODUCTNAME@@ port @@PORT@@ to start listening!"
    echo "Either @@PRODUCTNAME@@ did not load or this system is very slow."
fi
