#!/bin/bash

# Remove the old launchd plist if needed
JENKINS_PLIST="/Library/LaunchAgents/@@OSX_IDPREFIX@@.plist"
if [ -f ${JENKINS_PLIST} ]; then
	rm ${JENKINS_PLIST}
fi

JENKINS_DAEMON_PLIST="/Library/LaunchDaemons/@@OSX_IDPREFIX@@.plist"
launchctl unload ${JENKINS_DAEMON_PLIST} || echo 'Failed to unload old @@PRODUCTNAME@@ launch daemon. Maybe it is was not loaded?'
